pass0 = []
pass0.append("            # --- Pass 0: Low-conf YOLO -> HOLD ---\n")
pass0.append("            _prev_trusted_x = None\n")
pass0.append("            _phantom_yolo_frames = set()\n")
pass0.append("            for _fi in range(len(positions)):\n")
pass0.append("                _src = fusion_source_labels[_fi]\n")
pass0.append("                _conf = fusion_confidence[_fi]\n")
pass0.append("                if _src == 1 and _conf >= _PHANTOM_MIN_CONF:\n")
pass0.append("                    _prev_trusted_x = float(positions[_fi][0])\n")
pass0.append("                elif _src == 1 and _conf < _PHANTOM_MIN_CONF:\n")
pass0.append("                    _phantom_yolo_frames.add(_fi)\n")
pass0.append("                    if _prev_trusted_x is not None:\n")
pass0.append("                        positions[_fi][0] = _prev_trusted_x\n")
pass0.append("                    else:\n")
pass0.append("                        _af, _ax = _nearest_yolo_anchor(_fi)\n")
pass0.append("                        if _ax is not None:\n")
pass0.append("                            positions[_fi][0] = _ax\n")
pass0.append("                    fusion_source_labels[_fi] = 5\n")
pass0.append("                    fusion_confidence[_fi] = 0.3\n")
pass0.append("                    _phantom_fixes += 1\n")
pass0.append("                elif _src in (2, 3, 7) and _conf >= _PHANTOM_MIN_CONF:\n")
pass0.append("                    _prev_trusted_x = float(positions[_fi][0])\n")
pass0.append("\n")
