paths:
  video: examples/sample_game.mp4
  output_dir: examples/out

detect:
  min_gap: 1.0
  pre: 2.0
  post: 3.0
  max_count: 12
  audio_weight: 0.0
  threshold_std: 0.3
  hysteresis: 0.25
  sustain: 0.5

shrink:
  mode: smart
  pre: 2.0
  post: 3.0
  aspect: horizontal
  zoom: 1.0
  bias_blue: true

clips:
  min_duration: 2.0
  workers: 1

rank:
  k: 3
  max_len: 12.0
  min_tail: 4.0

reels:
  profile: broadcast
  topk_title: Sample Top Plays
